CREATE TABLE medicacao (
	idMedicacao INTEGER AUTO_INCREMENT PRIMARY KEY,
	descricao VARCHAR(255) NOT NULL,
	data_medicacao DATE NOT NULL,
	observacao VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE dieta (
	idDieta INTEGER AUTO_INCREMENT PRIMARY KEY,
	data_inicio DATE NOT NULL,
	data_fim DATE NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	observacao VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;




